config/routes.rb
HangmanWeb::Application.routes.draw do
  root :to => 'pages#home'

  resource :game, :only => [:create, :show] do
    resources :guesses, :only => [:create]
    get 'guesses', :to => 'guesses#create'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def start_game!
    session[:game] = Marshal.dump(Hangman.new_game)
  end

  def fetch_current_game
    Marshal.load session[:game]
  end

  def save_game(game)
    session[:game] = Marshal.dump(game)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    start_game!
    redirect_to game_url
  end

  def show
    @game = fetch_current_game
  end
  attr_reader :game
  helper_method :game
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  def create
    game = fetch_current_game
    game.guess(params[:letter])
    save_game game
    redirect_to game_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/show.html.haml
= image_tag "60px-Hangman-#{game.incorrect_guesses.size}.png", :alt => "#{6 - game.incorrect_guesses.size} guesses left"

#word
  - game.word.split('').each do |letter|
    = game.guesses.include?(letter) ? letter : '_'

%hr

%div
  - case game.status
  - when :won
    You win!
  - when :lost
    You lose!
  - else
    - ('a'..'z').each do |letter|
      - if game.guesses.include?(letter)
        %strike= letter
      - else
        = link_to letter, game_guesses_path(:letter => letter)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HangmanWeb
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = form_tag game_path do
      = button_tag 'Start a new game'

    %hr

    = yield